### PR TITLE
WIP - upgrade dependencies

### PR DESCRIPTION
**Pull request by dcharbonnier**
**Waiting for https://github.com/Teamwork/sharedb-mingo-memory/pull/1**
- Test the supported Nodejs versions only
- Limit the number of mongodb version test and add the current version
- Upgrade all packages

### CODE REVIEW

**Comment by curran** [comment]
@dcharbonnier CI is failing.

**Comment by dcharbonnier** [comment]
Yes thats why it's in WIP the other PR (https://github.com/Teamwork/sharedb-mingo-memory/pull/1) need to be merged first

**Comment by curran** [comment]
Aha I see. It feels a bit odd that `sharedb-mongo` has `sharedb-mingo-memory` as a dependency in the first place. Does that really make sense? Possible to split the shared testing logic into a separate package?

**Comment by gkubisa** [comment]
I've just merged and finished off this PR. Thanks @dcharbonnier :+1: 

A few things to note:

- published sharedb-mongo as v2.0.0 because the major version of MongoDB has changed, which could break backwards compatibility for some users.
- moved sharedb to peerDependencies to ensure sharedb-mongo is compatible with the version of sharedb used by the application.
- moved mongodb to peerDependencies to ensure that only one version of MongoDB is active in the application, which optimizes resource utilization and avoids surprises, eg differences in connection URL parsing.

> It feels a bit odd that sharedb-mongo has sharedb-mingo-memory as a dependency in the first place.

@curran, yes, testing-related dependencies are a bit odd in ShareDB in general and I'd like to address this in some way eventually. Maybe open an issue in ShareDB to highlight the problem and get people involved in figuring out a solution?

**Comment by curran** [comment]
Thanks @gkubisa !

Great move using peerDependencies, that solves some versioning issues I was having in fact.

**Pull request merged**
